name: Publish mem0-ts Package to GitHub Packages

# Trigger on new semver tags (e.g. v1.2.3) or manually
on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mem0-ts
    steps:
      # 1. Checkout the repo
      - uses: actions/checkout@v3

      # 2. Setup Node & point npm to GitHub Packages registry
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      # 3. Install dependencies & build in mem0-ts
      - run: npm install
      - run: npm run build

      - run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      # bump version before publishing, or ensure you've already incremented it
      - run: npm publish --access public
